# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marc Delagrammatikas
email: delagrammatikas@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Identity
your-name: Marc Delagrammatikas
your-title: Senior Software Engineer

# Social settings
500px_url:
facebook_url:
github_url: http://www.github.com/marcdel
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: http://www.linkedin.com/in/marcd
pinterest_url:
slack_url:
twitter_url: http://www.twitter.com/marcdel

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: marcdel
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
